from config.settings import *
from config.game_config import *
import pygame

ANCHO = SCREEN_WIDTH
ALTO = SCREEN_HEIGHT
MAP_ANCHO = MAP_WIDTH
MAP_ALTO = MAP_HEIGHT

AZUL1 = WATER_BLUE_LIGHT
AZUL2 = WATER_BLUE_DARK
VERDE = LAND_GREEN
SELVAS = JUNGLE_GREENS
TURBULENCIA = TURBULENCE_BLUE

NAVEGANTE_1 = BOAT_SPRITE_1
NAVEGANTE_2 = BOAT_SPRITE_2
VECTOR = pygame.math.Vector2
FULLSCREEN = FULLSCREEN_MODE