from config.game_config import *

BARCO_VEL = BOAT_SPEED_NORMAL
BARCO_VEL_TURBULENCIA = BOAT_SPEED_TURBULENCE
BARCO_VEL_ACELERON = BOAT_SPEED_BOOST

ANCHO_NAVEGANTE = BOAT_WIDTH
ALTO_NAVEGANTE = BOAT_HEIGHT

CREMA = UI_CREAM
NEGRO = UI_BLACK
NARANJA = UI_ORANGE